---
  - include: java7.yml

  - include: sbt_0.12.1.yml

  - name: Server | Create dir
    file: dest=$server_install_dir owner=$ansible_ssh_user group=$ansible_ssh_user mode=755 state=directory
    sudo: yes
    tags: server

  - name: Server | Checkout
    git: repo=$server_repo dest=$server_install_dir version=master
    register: checkout
    tags: server

  - name: Server | Copy upstart script
    action: template src=upstart.conf.j2 dest=/etc/init/rest-api.conf
    register: upstart
    sudo: yes
    tags: server

  - name:  Server | Generate start script
    action: command chdir=$server_install_dir sbt start-script
    when: checkout.changed
    tags: server
    notify: Server | Restart spray

