---
  - include: java7.yml
  
  - name: Jenkins | Check if is present
    command: test -x /etc/init.d/jenkins
    ignore_errors: yes
    register: jenkins_present
    tags: jenkins

  - name: Jenkins | Add GPG key to apt keyring
    shell: wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
    tags: jenkins
    when: jenkins_present|failed
    sudo: yes

  - name: Jenkins | Add apt repository
    copy: src=files/apt-source dest=/etc/apt/sources.list.d/jenkins.list mode=644
    tags: jenkins
    when: jenkins_present|failed
    sudo: yes

  - name: Jenkins | Create run dir
    command: mkdir -p /var/run/jenkins
    sudo: yes

  - name: Jenkins | Install
    apt: update-cache=yes force=yes state=present pkg=jenkins
    tags: jenkins
    when: jenkins_present|failed
    sudo: yes

  - name: Jenkins | Wait for start
    wait_for: port=8080 delay=30
    tags: jenkins
    when: jenkins_present|failed